Nfc: Use EXTRA_UNBOND_REASON instead of EXTRA_REASON
vendor/nxp/opensource/commonsys/packages/apps/Nfc/src/com/android/nfc/handover/BluetoothPeripheralHandover.java:493: error: cannot find symbol
                int reason = intent.getIntExtra(BluetoothDevice.EXTRA_REASON,
                                                               ^
  symbol:   variable EXTRA_REASON
  location: class BluetoothDevice
1 error

Ref:
https://android.googlesource.com/platform/packages/modules/Bluetooth/+/0c0220383389d4570649ed40d5b2d4223c04b4c2/framework/java/android/bluetooth/BluetoothDevice.java#405

Change-Id: Ie17f716e934add3c3eb3a82ac25adb74b6b47106